### ISSUE TITLE
Update Note on Supported Algorithms in [algorithm notes]

### ISSUE THREAD

**Issue by Be-Mann** [codemasher/php-googleauth#7]
**Description:**

The current note in the [algorithm notes](https://github.com/chillerlan/php-authenticator?tab=readme-ov-file#notes) mentions that several URI settings are not recognized by some authenticator apps. It should now be clarified that the Microsoft Authenticator app currently does not support certain algorithms. Therefore, it is recommended to use SHA1 as a fallback for compatibility with this app.

### Tasks:
- **Update note text:** Adjust the note text to accurately reflect the current support status of the Microsoft Authenticator app.
- **Add fallback method:** Explicitly mention that SHA1 should be used as a fallback for compatibility with the Microsoft Authenticator app.
  
**Current text:**
```
Keep in mind that several URI settings are not (yet) recognized by all authenticators. Check [the Google Authenticator wiki](https://github.com/google/google-authenticator/wiki/Key-Uri-Format#parameters) for more info.
```

**Proposed new text:**
```
Please note that the Microsoft Authenticator app currently does not support certain algorithms. It is recommended to use SHA1 as a fallback for compatibility with Microsoft Authenticator.
```

**Acceptance Criteria:**
- The note text is correctly updated to reflect the current support of the Microsoft Authenticator app.
- The SHA1 fallback is clearly and understandably stated.

**Comment by codemasher** [comment]
I don't see the point of this update. The note is for implementors of this library, not for end users. Further if we'd go down this route, we'd need to list every single 2FA application that might not support all of the settings, which might be all apps that are not "Google Authenticator".
